### ISSUE TITLE
not using optional db

### ISSUE THREAD

**Issue by JohnLandien** [Matsuo3rd/sms-forward#1]
Hello,

At first thank you for the code. I'm trying to expand to so it will auto answer on a incoming SMS.

While trying to do the first run, I changed the config and deleted macos ..... . In the readme you wrote it is optional.

when running node index.js I got the following error 
C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\lib\MacOSAdressBookLookup.js:29
        let db = new sqlite3.Database(macos_address_book_db_path, sqlite3.OPEN_READONLY, (err) => {
                 ^

TypeError: Argument 0 must be a string
    at loadAddressBookPhoneNumbers (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\lib\MacOSAdressBookLookup.js:29:11)
    at MacOSAdressBookLookup.init (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\lib\MacOSAdressBookLookup.js:16:2)
    at scanSMS (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\index.js:24:20)
    at Object.<anonymous> (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\index.js:20:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

I also tried to let macos .... stay in the JSON but making it "". Thisresults in : 
[2018-10-7 23:35:57] SMS Forward started
[2018-10-7 23:35:57] SQLITE_ERROR: no such table: ZABCDPHONENUMBER
C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\node_modules\sqlite3\lib\trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'ZFULLNUMBER' of undefined
    at db.each (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\lib\MacOSAdressBookLookup.js:57:47)
    at Statement.errBack (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\node_modules\sqlite3\lib\sqlite3.js:16:21)
--> in Database#each('SELECT DISTINCT\n\t\t\t\t\tZABCDRECORD.ZFIRSTNAME,\n\t\t\t\t\tZABCDRECORD.ZLASTNAME,\n\t\t\t\t\tZABCDRECORD.ZMAIDENNAME,\n\t\t\t\t\tZABCDRECORD.ZMIDDLENAME,\n\t\t\t\t\tZABCDRECORD.ZNICKNAME,\n\t\t\t\t\tZABCDRECORD.ZSUFFIX,\n\t\t\t\t\tZABCDRECORD.ZTITLE,\n\t\t\t\t\tZABCDRECORD.ZJOBTITLE,\n\t\t\t\t\tZABCDRECORD.ZORGANIZATION,\n\t\t\t\t\tZABCDPHONENUMBER.ZFULLNUMBER\n\t\t\t\tFROM ZABCDPHONENUMBER\n\t\t\t\tLEFT JOIN ZABCDRECORD ON ZABCDPHONENUMBER.ZOWNER = ZABCDRECORD.Z_PK', [Function])
    at Database.db.serialize (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\lib\MacOSAdressBookLookup.js:38:6)
    at loadAddressBookPhoneNumbers (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\lib\MacOSAdressBookLookup.js:37:5)
    at MacOSAdressBookLookup.init (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\lib\MacOSAdressBookLookup.js:16:2)
    at scanSMS (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\index.js:24:20)
    at Object.<anonymous> (C:\Users\johnl\AppData\Roaming\npm\node_modules\sms-forward\index.js:20:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

Maybe this is for you helpfull to rewrite de readme so I cant do it right, give an example of the db which must be included or rewrite a part of the code?

Regards,

John Langhout

**Comment by JohnLandien** [comment]
Sorry,

I didn't read you're read.me good enough.

I downloaded the code and I will try to get it working on Windows.

Regards,

John
